### ISSUE TITLE
Add a cool loading animation on splash screen

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#10]
Currently, the splash screen shows a very simple loading spinner.

Add some fancy animation for loading, you can use any flutter package or use flutter_flare and add a nice animation for loading.

**Comment by skohan** [comment]
Opened the pull request #11

**Comment by priyanshu0405** [comment]
Hey @mannprerak2, can I take this issue? Thanks!!

**Comment by mannprerak2** [comment]
Hi @priyanshu0405 
@sohan-k  is already working on this, please pick some other issue, they are all beginner friendly,
Thanks

**Comment by skohan** [comment]
You can assign me the issue @mannprerak2

**Comment by skohan** [comment]
Opened at #15
