### ISSUE TITLE
Hide upcoming event section if empty

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#12]
Currently the upcoming event tab shows `No upcoming Events`.

Hide or remove this section in case there are no upcoming events.

**Comment by AlKun25** [comment]
You can assign this issue to me @mannprerak2

**Comment by AgungPrabowo** [comment]
Hi @mannprerak2, can you assign me this issue?

**Comment by mannprerak2** [comment]
Sure

@AlKun25, I hope it's okay with you as you already have 2 issues assigned to you. I think I should let @AgungPrabowo work on this.

**Comment by AlKun25** [comment]
Yeah go ahead. It's fine with me

**Comment by AgungPrabowo** [comment]
thanks @mannprerak2 @AlKun25
