### ISSUE TITLE
Minor UI fixes

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#29]
The following small UI fixes are needed
- Add padding on the Spin Fade Cube (loader) widget in search delegate.
- The bell icon (subscribe button) should be placed at the extreme right in `society_tile_left`.
- Change the RaisedButton (`View all Societies` in `subs_tab` to be Red (`use Theme.of(context).primaryColor`) with white text.

**Comment by sans-23** [comment]
I want to work on this issue.

**Comment by mannprerak2** [comment]
Go ahead!

**Comment by sans-23** [comment]
I think Sirsho has done it.

**Comment by mannprerak2** [comment]
@sans-23 This issue was assigned to you, so **unless** you don't want to make a PR, I will only merge your PR.
So let me know if you'll be making a PR or not.
