### ISSUE TITLE
Add a "not available" message on Bookmark screen for Web

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#3]
The bookmark screen cannot work on Web as it uses SQLite to fetch data.

Show a "feature not available" message on the bookmark screen instead of it being stuck on loading forever

**Comment by skohan** [comment]
Hey @mannprerak2 , I can do this too! Please assign it to me!
And by bookmark you mean Saved tab right?

**Comment by mannprerak2** [comment]
>And by bookmark you mean Saved tab right?

Yes

**Comment by skohan** [comment]
Opened at #17
