### ISSUE TITLE
Hide Upcoming Events on Society Page if none are available

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#37]
The Society Page lists events of that society in 2 sections.
1. **Upcoming Events**
2. Past Events.

The upcoming events section currently shows "No Upcoming Events", instead of that, hide the upcoming events section if it's empty.

You can refer to #18 which handled this for the main screen.

**Comment by kb-hv** [comment]
Hi, can you assign this to me?

**Comment by mannprerak2** [comment]
Sure!
