### ISSUE TITLE
Add and use a placeholder image

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#4]
When the image link expires, no image is displayed and a white circle is seen (in thumbnails). Replace this with a placeholder image. 

The placeholder can either be from assets or be a network image, but it must be copyright free.

**Comment by ravindrabhargava** [comment]
Hi, @mannprerak2 Interesting!, can you give an example to understand it better, I would like to work on it now.

**Comment by mannprerak2** [comment]
Hi @ravindrabhargava ,
If you open this => https://mannprerak2.github.io/event_hub_flutter/#/ or compile and run the app on an android device.

You can see that certain images are not displayed and are blank. This is because the link for the URL for the image is invalid or has expired. So you need to apply a placeholder image to it in that case.

You would need to figure out how these images are being shown and loaded. And then add a way to handle the case where the URL doesn't render and show a placeholder image instead.

For the placeholder, you can use some copyright-free image, you can either use a network image or add an asset for this purpose.

**Comment by Himanshuranjan30** [comment]
I would like to fix this for you @mannprerak2

**Comment by mannprerak2** [comment]
Sure, go ahead @Himanshuranjan30

**Comment by AlKun25** [comment]
I have made a pull request to close this issue, though I would say not to use an image as placeholder. <br>
You could show some **loading spinner** as _placeholder_ in _CachedNetworkImage_.<br>
And rather use **images** to be loaded as _errorWidget_ in _CachedNetworkImage_.<br>

**Comment by AlKun25** [comment]
I will be making the PR soon. For this Issue. You can assign this to me @mannprerak2
