### ISSUE TITLE
Show bookmarking/subscribing not available on web

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#5]
The bookmark button or subscribe button do not work on web, because they store information on sqlite.

We should handle these buttons on web and instead show a snackbar or a popup saying that this feature is not available on web.

**Comment by AlKun25** [comment]
I would like to also work on this issue, but isn't this same as the #3

**Comment by mannprerak2** [comment]
`#3` is to show a message on the entire bookmarks screen actually, this issue involves showing a popup/snackbar when someone clicks the bookmark button or subscribe button (the buttons in event/society pages and tiles, not the bottom bar button)

**Comment by AlKun25** [comment]
Assign this one too @mannprerak2
