### ISSUE TITLE
Fix Icons for web(favicon) and android(launcher icon)

### ISSUE THREAD

**Issue by mannprerak2** [mannprerak2/event_hub_flutter#6]
Currently, the default Flutter icon is shown as favicon(web) or launcher icon(android). Replace them with the actual icons.
The icons to be used can be found in `assets` directory.

**Comment by Sirsho29** [comment]
Hi, I want to solve this issue.

**Comment by mannprerak2** [comment]
Sure, go ahead @Sirsho29 (I presume after 1st October)

**Comment by Sirsho29** [comment]
Hacktoberfest has already started. So I think I can solve now

**Comment by Sirsho29** [comment]
I have created a PR. Please check and accept it. I have completed the web icon part.

**Comment by mannprerak2** [comment]
Please complete the android icon part as well in the same PR.

Btw, hacktoberfest begins on 1st October, any PR's made before will probably not be counted. (I am not sure)

**Comment by Sirsho29** [comment]
I just completed the android part.

I got a mail from digital ocean about start of the hacktoberfest and in their website also its showing that it has started. Even I knew that it starts from 1st october.

**Comment by mannprerak2** [comment]
Closed by #8
